DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS volumeinfo;
DROP TABLE IF EXISTS industryIdentifiers;
DROP TABLE IF EXISTS readingModes;
DROP TABLE IF EXISTS panelizationSummary;
DROP TABLE IF EXISTS imageLinks;
DROP TABLE IF EXISTS maturityRating;
DROP TABLE IF EXISTS printType;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS saleInfo;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS saleability;
DROP TABLE IF EXISTS accessInfo;
DROP TABLE IF EXISTS viewability;
DROP TABLE IF EXISTS textToSpeechPermission;


CREATE TABLE book (
id TEXT(12) PRIMARY KEY NOT NULL,
kind TEXT(15) NOT NULL,
etag TEXT(20) NOT NULL,
selflink TEXT(75) NOT NULL);

CREATE TABLE volumeinfo (
bookId TEXT(12) NOT NULL,
title TEXT(50) NOT NULL,
publishedDate DATE(10) NOT NULL,
desc BLOB NOT NULL,
pageCount INTEGER NOT NULL,
printType INTEGER NOT NULL,
maturityRating INTEGER NOT NULL,
allowAnonLoggin BOOLEAN NOT NULL DEFAULT false,
contentVerison TEXT(25) NOT NULL,
language TEXT(3) NOT NULL,
previewLink TEXT(50) NOT NULL,
infoLink TEXT(50) NOT NULL,
canonicalVolumeLink TEXT NOT NULL,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(printType) REFERENCES printType(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(maturityRating) REFERENCES maturityRating(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE industryIdentifiers (
bookId TEXT(12) NOT NULL,
type TEXT(25) NOT NULL,
identifier TEXT(25) NOT NULL,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE readingModes (
bookId TEXT(12) NOT NULL,
text BOOLEAN NOT NULL DEFAULT false,
image BOOLEAN NOT NULL DEFAULT false,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE panelizationSummary (
bookId TEXT(12) NOT NULL,
containsEpubBubbles BOOLEAN NOT NULL,
containsImageBubbles BOOLEAN NOT NULL,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE imageLinks (
bookId TEXT(12) NOT NULL,
smallThumbnail TEXT(50) NOT NULL,
thumbnail TEXT(50) NOT NULL,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE maturityRating (
id INTEGER(12) PRIMARY KEY NOT NULL,
rating TEXT(25) NOT NULL);

CREATE TABLE printType (
id INTEGER PRIMARY KEY NOT NULL,
type INTEGER(20) NOT NULL);

CREATE TABLE authors (
bookId TEXT(12) NOT NULL,
Name INTEGER(25) NOT NULL,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE saleInfo (
bookId TEXT(12) NOT NULL,
country INTEGER NOT NULL,
saleability INTEGER NOT NULL,
isEbook BOOLEAN NOT NULL DEFAULT false,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(country) REFERENCES country(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(saleability) REFERENCES saleability(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE country (
id INTEGER PRIMARY KEY NOT NULL,
short TEXT(2) NOT NULL,
long TEXT(25) NOT NULL);

CREATE TABLE saleability (
id INTEGER PRIMARY KEY NOT NULL,
name TEXT(25) NOT NULL);

CREATE TABLE accessInfo (
bookId TEXT(12) NOT NULL,
country INTEGER NOT NULL,
viewability INTEGER NOT NULL,
textToSpeachPermission INTEGER NOT NULL,
embeddable BOOLEAN NOT NULL DEFAULT false,
publicDomain BOOLEAN NOT NULL DEFAULT false,
FOREIGN KEY(bookId) REFERENCES book(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(country) REFERENCES country(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(viewability) REFERENCES viewability(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(textToSpeachPermission) REFERENCES textToSpeechPermission(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE viewability (
id INTEGER PRIMARY KEY NOT NULL,
type INTEGER NOT NULL);

CREATE TABLE textToSpeechPermission (
id INTEGER PRIMARY KEY NOT NULL,
permission INTEGER NOT NULL);

