DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Reader;


CREATE TABLE Book (
id INTEGER PRIMARY KEY NOT NULL,
readerId INTEGER NOT NULL,
ISBN TEXT(13) NOT NULL,
Title TEXT(50) NOT NULL,
Desc BLOB NOT NULL,
ThumbNailURL TEXT(50) NOT NULL,
FOREIGN KEY(readerId) REFERENCES Reader(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE Reader (
id INTEGER PRIMARY KEY NOT NULL,
Firstname TEXT(50) NOT NULL,
LastName TEXT(50) NOT NULL);

